
package co.com.parking.parkingpractice.superintendencia;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TCRMServicesWebService", targetNamespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", wsdlLocation = "META-INF/wsdl/TCRMServicesWebService.wsdl")
public class TCRMServicesWebService
    extends Service
{

    private final static URL TCRMSERVICESWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TCRMSERVICESWEBSERVICE_EXCEPTION;
    private final static QName TCRMSERVICESWEBSERVICE_QNAME = new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TCRMServicesWebService");

    static {
        TCRMSERVICESWEBSERVICE_WSDL_LOCATION = co.com.parking.parkingpractice.superintendencia.TCRMServicesWebService.class.getClassLoader().getResource("META-INF/wsdl/TCRMServicesWebService.wsdl");
        WebServiceException e = null;
        if (TCRMSERVICESWEBSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TCRMServicesWebService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TCRMSERVICESWEBSERVICE_EXCEPTION = e;
    }

    public TCRMServicesWebService() {
        super(__getWsdlLocation(), TCRMSERVICESWEBSERVICE_QNAME);
    }

    public TCRMServicesWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TCRMSERVICESWEBSERVICE_QNAME, features);
    }

    public TCRMServicesWebService(URL wsdlLocation) {
        super(wsdlLocation, TCRMSERVICESWEBSERVICE_QNAME);
    }

    public TCRMServicesWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TCRMSERVICESWEBSERVICE_QNAME, features);
    }

    public TCRMServicesWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TCRMServicesWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TCRMServicesInterface
     */
    @WebEndpoint(name = "TCRMServicesWebServicePort")
    public TCRMServicesInterface getTCRMServicesWebServicePort() {
        return super.getPort(new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TCRMServicesWebServicePort"), TCRMServicesInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TCRMServicesInterface
     */
    @WebEndpoint(name = "TCRMServicesWebServicePort")
    public TCRMServicesInterface getTCRMServicesWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TCRMServicesWebServicePort"), TCRMServicesInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TCRMSERVICESWEBSERVICE_EXCEPTION!= null) {
            throw TCRMSERVICESWEBSERVICE_EXCEPTION;
        }
        return TCRMSERVICESWEBSERVICE_WSDL_LOCATION;
    }

}
