
package co.com.parking.parkingpractice.superintendencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TCRMServicesInterface", targetNamespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TCRMServicesInterface {


    /**
     * 
     * @param tcrmQueryAssociatedDate
     * @return
     *     returns co.com.parking.parkingpractice.superintendencia.TcrmResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTCRM", targetNamespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", className = "co.com.parking.parkingpractice.superintendencia.QueryTCRM")
    @ResponseWrapper(localName = "queryTCRMResponse", targetNamespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", className = "co.com.parking.parkingpractice.superintendencia.QueryTCRMResponse")
    public TcrmResponse queryTCRM(
        @WebParam(name = "tcrmQueryAssociatedDate", targetNamespace = "")
        XMLGregorianCalendar tcrmQueryAssociatedDate);

}
